database:
  host: "agilely.com"
  port: "27017"
  name: "poller_development"

server:
  host: "agilely.com"
  port: "5000"
  api:
    subdomain: "api."
  static:
    subdomain: ""
    homepage: "/"
    buildpath: "web/build"
    manifestpath: "web/build/asset-manifest.json"
